WebAPP_Marjorie_Falcone_202496/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI__Marjorie_Falcone_202496.Models
{
   
    public class Cliente
    {
        public Cliente()
        {
            Prestamos = new HashSet<Prestamo>();
        }
      
        public int IdCliente { get; set; }
        public string Nombre { get; set; } = null!;
        public string CorreoElectronico { get; set; } = null!;
        public string Usuario { get; set; } = null!;
        public string Contraseña { get; set; } = null!;

        public virtual ICollection<Prestamo> Prestamos { get; set; }
    }
}

WebAPP_Marjorie_Falcone_202496/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAPI__Marjorie_Falcone_202496.Models;
using WebAPP_Marjorie_Falcone_202496.Data;
using WebAPP_Marjorie_Falcone_202496.Service.Clientes;

namespace WebAPP_Marjorie_Falcone_202496.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClienteServices _ClienteService;

        public ClientesController(IClienteServices ClienteService)
        {
            _ClienteService = ClienteService;
        }


        public async Task<IActionResult> Actualizar([FromBody] Cliente Cliente)
        {
            var Clientes = await _ClienteService.Actualizar(Cliente);
            return Json(Clientes);
        }

        public async Task<IActionResult> Ver(int codigo)
        {
            var Clientes = await _ClienteService.ver(codigo);
            return Json(Clientes);
        }

        public async Task<IActionResult> Index()
        {
            var Clientes = await _ClienteService.ConsultarTodos();
            return View(Clientes);

        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Guardar([FromBody] Cliente Cliente)
        {
            var Clientes = await _ClienteService.Crear(Cliente);
            return Json(Clientes);
        }


    }
}

WebAPP_Marjorie_Falcone_202496/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAPP_Marjorie_Falcone_202496.Models;

namespace WebAPP_Marjorie_Falcone_202496.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        public IActionResult Administrador()
        {
            return View();
        }

        public IActionResult Cliente()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAPP_Marjorie_Falcone_202496/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAPI__Marjorie_Falcone_202496.Models;
using WebAPP_Marjorie_Falcone_202496.Data;

namespace WebAPP_Marjorie_Falcone_202496.Controllers
{
    public class PagosController : Controller
    {
        private readonly WebAPP_Marjorie_Falcone_202496Context _context;

        public PagosController(WebAPP_Marjorie_Falcone_202496Context context)
        {
            _context = context;
        }

        // GET: Pagoes
        public async Task<IActionResult> Index()
        {
              return _context.Pago != null ? 
                          View(await _context.Pago.ToListAsync()) :
                          Problem("Entity set 'WebAPP_Marjorie_Falcone_202496Context.Pago'  is null.");
        }

        // GET: Pagoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pago == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago
                .FirstOrDefaultAsync(m => m.IdPago == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // GET: Pagoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pagoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPago,IdPrestamo,FechaPago,Monto,Capital,Interes,Comisiones")] Pago pago)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pago);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pago);
        }

        // GET: Pagoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pago == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago.FindAsync(id);
            if (pago == null)
            {
                return NotFound();
            }
            return View(pago);
        }

        // POST: Pagoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPago,IdPrestamo,FechaPago,Monto,Capital,Interes,Comisiones")] Pago pago)
        {
            if (id != pago.IdPago)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagoExists(pago.IdPago))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pago);
        }

        // GET: Pagoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pago == null)
            {
                return NotFound();
            }

            var pago = await _context.Pago
                .FirstOrDefaultAsync(m => m.IdPago == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // POST: Pagoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pago == null)
            {
                return Problem("Entity set 'WebAPP_Marjorie_Falcone_202496Context.Pago'  is null.");
            }
            var pago = await _context.Pago.FindAsync(id);
            if (pago != null)
            {
                _context.Pago.Remove(pago);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagoExists(int id)
        {
          return (_context.Pago?.Any(e => e.IdPago == id)).GetValueOrDefault();
        }
    }
}

WebAPP_Marjorie_Falcone_202496/Controllers/PrestamosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAPI__Marjorie_Falcone_202496.Models;
using WebAPP_Marjorie_Falcone_202496.Data;

namespace WebAPP_Marjorie_Falcone_202496.Controllers
{
    public class PrestamosController : Controller
    {
        private readonly WebAPP_Marjorie_Falcone_202496Context _context;

        public PrestamosController(WebAPP_Marjorie_Falcone_202496Context context)
        {
            _context = context;
        }

        // GET: Prestamoes
        public async Task<IActionResult> Index()
        {
              return _context.Prestamo != null ? 
                          View(await _context.Prestamo.ToListAsync()) :
                          Problem("Entity set 'WebAPP_Marjorie_Falcone_202496Context.Prestamo'  is null.");
        }

        // GET: Prestamoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Prestamo == null)
            {
                return NotFound();
            }

            var prestamo = await _context.Prestamo
                .FirstOrDefaultAsync(m => m.IdPrestamo == id);
            if (prestamo == null)
            {
                return NotFound();
            }

            return View(prestamo);
        }

        // GET: Prestamoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Prestamoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPrestamo,Monto,Plazo,TasaInteres,Estado,IdCliente")] Prestamo prestamo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(prestamo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(prestamo);
        }

        // GET: Prestamoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Prestamo == null)
            {
                return NotFound();
            }

            var prestamo = await _context.Prestamo.FindAsync(id);
            if (prestamo == null)
            {
                return NotFound();
            }
            return View(prestamo);
        }

        // POST: Prestamoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPrestamo,Monto,Plazo,TasaInteres,Estado,IdCliente")] Prestamo prestamo)
        {
            if (id != prestamo.IdPrestamo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prestamo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrestamoExists(prestamo.IdPrestamo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prestamo);
        }

        // GET: Prestamoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Prestamo == null)
            {
                return NotFound();
            }

            var prestamo = await _context.Prestamo
                .FirstOrDefaultAsync(m => m.IdPrestamo == id);
            if (prestamo == null)
            {
                return NotFound();
            }

            return View(prestamo);
        }

        // POST: Prestamoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Prestamo == null)
            {
                return Problem("Entity set 'WebAPP_Marjorie_Falcone_202496Context.Prestamo'  is null.");
            }
            var prestamo = await _context.Prestamo.FindAsync(id);
            if (prestamo != null)
            {
                _context.Prestamo.Remove(prestamo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PrestamoExists(int id)
        {
          return (_context.Prestamo?.Any(e => e.IdPrestamo == id)).GetValueOrDefault();
        }
    }
}

WebAPP_Marjorie_Falcone_202496/Views/Home/Administrador.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Préstamos - Inicio</title>
    <!-- Cargar Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .card-custom {
            margin: 20px;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            transition: 0.3s;
        }

            .card-custom:hover {
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            }

        .card-img-top {
            border-radius: 50%;
            width: 50%;
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <div class="container mt-5">
        <h2 class="text-center mb-4">Gestión de Préstamos Bancarios</h2>

        <div class="row justify-content-center">
            <!-- Card para Cliente -->
            <div class="col-md-4">
                <div class="card card-custom">
                    <img src="https://static.vecteezy.com/system/resources/previews/014/649/447/non_2x/outsource-manager-icon-simple-style-vector.jpg" class="card-img-top mx-auto" alt="Administrador">
                    <div class="card-body">
                        <h5 class="card-title">Cliente</h5>
                        <p class="card-text">Accede a clientes</p>
                        <a asp-controller="Clientes" asp-action="Index" class="btn btn-primary">Cliente</a>
                    </div>
                </div>
            </div>

            <!-- Card para Administrador -->
            <div class="col-md-4">
                <div class="card card-custom">
                    <img src="https://static.vecteezy.com/system/resources/previews/014/649/447/non_2x/outsource-manager-icon-simple-style-vector.jpg" class="card-img-top mx-auto" alt="Administrador">
                    <div class="card-body">
                        <h5 class="card-title">Pagos</h5>
                        <p class="card-text">revisar pagos</p>
                        <a asp-controller="Pagos" asp-action="Index" class="btn btn-success">Pagos</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-custom">
                    <img src="https://static.vecteezy.com/system/resources/previews/014/649/447/non_2x/outsource-manager-icon-simple-style-vector.jpg" class="card-img-top mx-auto" alt="Administrador">
                    <div class="card-body">
                        <h5 class="card-title">Prestamos</h5>
                        <p class="card-text">gestionar solicitudes de préstamos</p>
                        <a asp-controller="Prestamos" asp-action="Index" class="btn btn-success">Prestamos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Cargar Bootstrap JS y dependencias de Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

WebAPP_Marjorie_Falcone_202496/Views/Home/Cliente.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Préstamos - Inicio</title>
    <!-- Cargar Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .card-custom {
            margin: 20px;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            transition: 0.3s;
        }

            .card-custom:hover {
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            }

        .card-img-top {
            border-radius: 50%;
            width: 50%;
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <div class="container mt-5">
        <h2 class="text-center mb-4">Gestión de Préstamos Bancarios</h2>

        <div class="row justify-content-center">
            <!-- Card para Cliente -->
            <div class="col-md-4">
                <div class="card card-custom">
                    <img src="https://static.vecteezy.com/system/resources/previews/014/649/447/non_2x/outsource-manager-icon-simple-style-vector.jpg" class="card-img-top mx-auto" alt="Administrador">
                    <div class="card-body">
                        <h5 class="card-title">Prestamos</h5>
                        <p class="card-text">solicitudes Prestamos</p>
                        <a asp-controller="Prestamos" asp-action="Create" class="btn btn-primary">Prestamos</a>
                    </div>
                </div>
            </div>

            <!-- Card para Administrador -->
            <div class="col-md-4">
                <div class="card card-custom">
                    <img src="https://static.vecteezy.com/system/resources/previews/014/649/447/non_2x/outsource-manager-icon-simple-style-vector.jpg" class="card-img-top mx-auto" alt="Administrador">
                    <div class="card-body">
                        <h5 class="card-title">Pagos</h5>
                        <p class="card-text">revisar pagos</p>
                        <a asp-controller="Pagos" asp-action="Index" class="btn btn-success">Pagos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Cargar Bootstrap JS y dependencias de Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

WebAPP_Marjorie_Falcone_202496/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="card p-4 shadow-sm" style="max-width: 400px; width: 100%;">
            <h2 class="text-center mb-4">Login</h2>
            <form>
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter your email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Enter your password" required>
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary" asp-controller="Home" asp-action="Privacy">Login</button>
                </div>
                <div class="mt-3 text-center">
                    <a href="#" class="text-muted">Forgot your password?</a>
                </div>
            </form>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>